name: Bug Report
description: Create a report to help us improve
body:
  - type: markdown
    attributes:
      value: |
        Hi, thank you for taking the time to create an issue! Please make sure to fill out this form in as much detail you can. 

        _For issues specific to Directus Cloud projects, please reach out through the Live Chat in our Cloud Dashboard._
  - type: checkboxes
    id: requirements
    attributes:
      label: Checklist
      options:
        - label: I'm using the [latest version of Directus](https://github.com/directus/directus/releases)
          required: true
        - label: There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes the problem.
          required: true
        - label: I've completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
          required: true
  - type: textarea
    attributes:
      label: Describe the Bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    attributes:
      label: To Reproduce
      description:
        Steps to reproduce the behavior. Contributors should be able to follow the steps provided in order to reproduce
        the bug.
    validations:
      required: true
  - type: dropdown
    id: deployment
    attributes:
      label: Hosting Strategy
      options:
        - Self-Hosted (Docker Image)
        - Self-Hosted (Custom)
        - Directus Cloud
    validations:
      required: true
